hmc.java.versions=/usr/lib/jvm/java-21-openjdk-amd64/bin/java;/usr/lib/jvm/java-1.21.0-openjdk-amd64/bin/java
hmc.offline=true
hmc.offline.username=HeadlessBuilderExample
hmc.offline.uuid=21aba0fbe87f35f9837e8e78f7e22cad